image: ruby:2.3

test:
  stage: test
  script:
    - gem install bundler
    - bundle install
    - jekyll build -d test
  artifacts:
    paths:
      - test
  except:
    - master

pages:
  stage: deploy
  script:
    - gem install bundler
    - bundle install
    - jekyll build -d public --config _config.gitlab.yml
  artifacts:
    paths:
      - public
  except:
    - master

rsync_to_blog:
  stage: deploy
  script:
    - gem install bundler
    - bundle install
    - jekyll build
    - echo $SSH_KEY_TERIIEHINA_BLOG_CI > ~/.ssh/id_rsa
    - ssh-add ~/.ssh/id_rsa
    - rsync -r ./_site/* teriiehina_blog@teriiehina.blog:~/teriiehina.blog
  only:
    - master
