image: ruby:2.3

pages:
  stage: deploy
  environment: staging
  script:
    - gem install bundler
    - bundle install
    - jekyll build -d public --config _config.gitlab.yml
  artifacts:
    paths:
      - public

rsync_to_blog:
  stage: deploy
  environment: production
  script:
    - gem install bundler
    - bundle install
    - jekyll build
    - echo $SSH_KEY_TERIIEHINA_BLOG_CI > ~/id_rsa
    - ssh-add ~/id_rsa
    - rsync -r ./_site/* teriiehina_blog@teriiehina.blog:~/teriiehina.blog
  only:
    - master
